(function () {
    "use strict"; // buy  status service

    angular
        .module("app")
        .value("toyData",
        [
            {
                "id": 1,
                "gender": "Male",
                "first_name": "Jason",
                "last_name": "Sullivan",
                "email": "jsullivan0@aboutads.info",
                "ip_address": "202.79.27.19"
            }, {
                "id": 2,
                "gender": "Female",
                "first_name": "Lori",
                "last_name": "Hill",
                "email": "lhill1@theguardian.com",
                "ip_address": "128.193.137.248"
            }, {
                "id": 3,
                "gender": "Male",
                "first_name": "Arthur",
                "last_name": "Morris",
                "email": "amorris2@nbcnews.com",
                "ip_address": "143.79.81.220"
            }, {
                "id": 4,
                "gender": "Female",
                "first_name": "Julie",
                "last_name": "Andrews",
                "email": "jandrews3@domainmarket.com",
                "ip_address": "14.169.136.139"
            }, {
                "id": 5,
                "gender": "Male",
                "first_name": "Clarence",
                "last_name": "Evans",
                "email": "cevans4@loc.gov",
                "ip_address": "126.54.166.50"
            }, {
                "id": 6,
                "gender": "Male",
                "first_name": "Russell",
                "last_name": "Sims",
                "email": "rsims5@yahoo.co.jp",
                "ip_address": "130.11.29.222"
            }, {
                "id": 7,
                "gender": "Female",
                "first_name": "Denise",
                "last_name": "Henry",
                "email": "dhenry6@ycombinator.com",
                "ip_address": "79.226.68.54"
            }, {
                "id": 8,
                "gender": "Male",
                "first_name": "Raymond",
                "last_name": "Meyer",
                "email": "rmeyer7@earthlink.net",
                "ip_address": "63.172.63.57"
            }, {
                "id": 9,
                "gender": "Male",
                "first_name": "Chris",
                "last_name": "Jones",
                "email": "cjones8@geocities.com",
                "ip_address": "229.97.176.234"
            }, {
                "id": 10,
                "gender": "Male",
                "first_name": "Eric",
                "last_name": "Powell",
                "email": "epowell9@php.net",
                "ip_address": "100.28.114.99"
            }, {
                "id": 11,
                "gender": "Female",
                "first_name": "Kathryn",
                "last_name": "Hansen",
                "email": "khansena@twitter.com",
                "ip_address": "114.37.75.138"
            }, {
                "id": 12,
                "gender": "Male",
                "first_name": "Joseph",
                "last_name": "Gibson",
                "email": "jgibsonb@gmpg.org",
                "ip_address": "98.106.191.43"
            }, {
                "id": 13,
                "gender": "Male",
                "first_name": "Steve",
                "last_name": "Duncan",
                "email": "sduncanc@comsenz.com",
                "ip_address": "190.242.251.163"
            }, {
                "id": 14,
                "gender": "Female",
                "first_name": "Lori",
                "last_name": "Watson",
                "email": "lwatsond@walmart.com",
                "ip_address": "57.25.63.118"
            }, {
                "id": 15,
                "gender": "Male",
                "first_name": "Donald",
                "last_name": "Peters",
                "email": "dpeterse@icq.com",
                "ip_address": "189.100.83.51"
            }, {
                "id": 16,
                "gender": "Male",
                "first_name": "Shawn",
                "last_name": "Chavez",
                "email": "schavezf@cbsnews.com",
                "ip_address": "34.250.177.113"
            }, {
                "id": 17,
                "gender": "Male",
                "first_name": "David",
                "last_name": "Porter",
                "email": "dporterg@nationalgeographic.com",
                "ip_address": "202.153.148.72"
            }, {
                "id": 18,
                "gender": "Male",
                "first_name": "Stephen",
                "last_name": "Rodriguez",
                "email": "srodriguezh@newyorker.com",
                "ip_address": "82.87.92.134"
            }, {
                "id": 19,
                "gender": "Male",
                "first_name": "Samuel",
                "last_name": "Mcdonald",
                "email": "smcdonaldi@nifty.com",
                "ip_address": "75.94.148.220"
            }, {
                "id": 20,
                "gender": "Male",
                "first_name": "Gary",
                "last_name": "Simpson",
                "email": "gsimpsonj@weather.com",
                "ip_address": "164.44.126.193"
            }, {
                "id": 21,
                "gender": "Male",
                "first_name": "Stephen",
                "last_name": "Kim",
                "email": "skimk@weibo.com",
                "ip_address": "232.160.119.222"
            }, {
                "id": 22,
                "gender": "Male",
                "first_name": "Carl",
                "last_name": "Hamilton",
                "email": "chamiltonl@columbia.edu",
                "ip_address": "19.139.86.192"
            }, {
                "id": 23,
                "gender": "Female",
                "first_name": "Lisa",
                "last_name": "Wagner",
                "email": "lwagnerm@psu.edu",
                "ip_address": "231.135.219.84"
            }, {
                "id": 24,
                "gender": "Male",
                "first_name": "Victor",
                "last_name": "Willis",
                "email": "vwillisn@va.gov",
                "ip_address": "229.70.52.197"
            }, {
                "id": 25,
                "gender": "Male",
                "first_name": "Jeffrey",
                "last_name": "Baker",
                "email": "jbakero@examiner.com",
                "ip_address": "248.212.183.134"
            }, {
                "id": 26,
                "gender": "Male",
                "first_name": "Christopher",
                "last_name": "Fernandez",
                "email": "cfernandezp@blogs.com",
                "ip_address": "157.173.85.108"
            }, {
                "id": 27,
                "gender": "Female",
                "first_name": "Sharon",
                "last_name": "Campbell",
                "email": "scampbellq@census.gov",
                "ip_address": "185.188.22.200"
            }, {
                "id": 28,
                "gender": "Male",
                "first_name": "Peter",
                "last_name": "Tucker",
                "email": "ptuckerr@scientificamerican.com",
                "ip_address": "173.243.234.156"
            }, {
                "id": 29,
                "gender": "Male",
                "first_name": "Charles",
                "last_name": "Montgomery",
                "email": "cmontgomerys@netlog.com",
                "ip_address": "124.158.152.0"
            }, {
                "id": 30,
                "gender": "Male",
                "first_name": "Walter",
                "last_name": "Cooper",
                "email": "wcoopert@biblegateway.com",
                "ip_address": "221.164.182.136"
            }, {
                "id": 31,
                "gender": "Female",
                "first_name": "Ruth",
                "last_name": "West",
                "email": "rwestu@barnesandnoble.com",
                "ip_address": "140.215.101.10"
            }, {
                "id": 32,
                "gender": "Male",
                "first_name": "Steven",
                "last_name": "Gardner",
                "email": "sgardnerv@samsung.com",
                "ip_address": "216.15.172.61"
            }, {
                "id": 33,
                "gender": "Male",
                "first_name": "Nicholas",
                "last_name": "Black",
                "email": "nblackw@hostgator.com",
                "ip_address": "231.186.222.19"
            }, {
                "id": 34,
                "gender": "Female",
                "first_name": "Teresa",
                "last_name": "Mason",
                "email": "tmasonx@topsy.com",
                "ip_address": "247.104.5.226"
            }, {
                "id": 35,
                "gender": "Male",
                "first_name": "Carlos",
                "last_name": "Cox",
                "email": "ccoxy@sourceforge.net",
                "ip_address": "202.243.138.199"
            }, {
                "id": 36,
                "gender": "Female",
                "first_name": "Michelle",
                "last_name": "Hicks",
                "email": "mhicksz@plala.or.jp",
                "ip_address": "99.163.45.1"
            }, {
                "id": 37,
                "gender": "Female",
                "first_name": "Cheryl",
                "last_name": "Griffin",
                "email": "cgriffin10@tinypic.com",
                "ip_address": "69.59.124.12"
            }, {
                "id": 38,
                "gender": "Female",
                "first_name": "Nancy",
                "last_name": "Burton",
                "email": "nburton11@state.tx.us",
                "ip_address": "58.235.170.87"
            }, {
                "id": 39,
                "gender": "Female",
                "first_name": "Dorothy",
                "last_name": "Arnold",
                "email": "darnold12@yellowbook.com",
                "ip_address": "180.41.50.17"
            }, {
                "id": 40,
                "gender": "Female",
                "first_name": "Kathleen",
                "last_name": "Peters",
                "email": "kpeters13@vk.com",
                "ip_address": "237.122.229.7"
            }, {
                "id": 41,
                "gender": "Male",
                "first_name": "Philip",
                "last_name": "Nguyen",
                "email": "pnguyen14@imdb.com",
                "ip_address": "116.148.217.39"
            }, {
                "id": 42,
                "gender": "Male",
                "first_name": "Russell",
                "last_name": "Rose",
                "email": "rrose15@myspace.com",
                "ip_address": "89.124.6.25"
            }, {
                "id": 43,
                "gender": "Male",
                "first_name": "Harry",
                "last_name": "Anderson",
                "email": "handerson16@blogspot.com",
                "ip_address": "199.117.133.234"
            }, {
                "id": 44,
                "gender": "Female",
                "first_name": "Michelle",
                "last_name": "Wood",
                "email": "mwood17@cisco.com",
                "ip_address": "242.183.120.84"
            }, {
                "id": 45,
                "gender": "Male",
                "first_name": "Steven",
                "last_name": "Patterson",
                "email": "spatterson18@nih.gov",
                "ip_address": "51.6.233.166"
            }, {
                "id": 46,
                "gender": "Male",
                "first_name": "Lawrence",
                "last_name": "Dixon",
                "email": "ldixon19@clickbank.net",
                "ip_address": "89.10.180.221"
            }, {
                "id": 47,
                "gender": "Female",
                "first_name": "Robin",
                "last_name": "Gardner",
                "email": "rgardner1a@bloglovin.com",
                "ip_address": "187.13.99.190"
            }, {
                "id": 48,
                "gender": "Male",
                "first_name": "Benjamin",
                "last_name": "Phillips",
                "email": "bphillips1b@wikipedia.org",
                "ip_address": "59.169.113.77"
            }, {
                "id": 49,
                "gender": "Male",
                "first_name": "Michael",
                "last_name": "Daniels",
                "email": "mdaniels1c@bloomberg.com",
                "ip_address": "234.16.3.221"
            }, {
                "id": 50,
                "gender": "Male",
                "first_name": "George",
                "last_name": "Shaw",
                "email": "gshaw1d@google.it",
                "ip_address": "160.247.207.153"
            }
        ]);


}());